wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.9
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727681543.807886
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.6.9
      5: 0.14.2
      8:
      - 5
    visualize:
      Predicted:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/scatter/v0
          fieldSettings:
            x: Easting
            y: Northing
          stringSettings:
            title: null
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Predicted_table
                fields: []
      Labels:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/scatter/v0
          fieldSettings:
            x: Easting
            y: Northing
          stringSettings:
            title: null
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Labels_table
                fields: []
